<a href="https://colab.research.google.com/github/shivansh858/ML_supervised-learning-/blob/main/ML_project3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.drop(['deck','alive','embarked', "class", "who", "adult_male"], axis=1, inplace=True)
df.head()

   survived  pclass     sex   age  sibsp  parch     fare  embark_town  alone
0         0       3    male  22.0      1      0   7.2500  Southampton  False
1         1       1  female  38.0      1      0  71.2833    Cherbourg  False
2         1       3  female  26.0      0      0   7.9250  Southampton   True
3         1       1  female  35.0      1      0  53.1000  Southampton  False
4         0       3    male  35.0      0      0   8.0500  Southampton   True

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embark_town      2
alone            0
dtype: int64

In [ ]:
df.fillna(df['age'].mean(),inplace=True)
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embark_town    0
alone          0
dtype: int64

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare  embark_town  alone
0         0       3    male  22.0      1      0   7.2500  Southampton  False
1         1       1  female  38.0      1      0  71.2833    Cherbourg  False
2         1       3  female  26.0      0      0   7.9250  Southampton   True
3         1       1  female  35.0      1      0  53.1000  Southampton  False
4         0       3    male  35.0      0      0   8.0500  Southampton   True

In [ ]:
df_en=pd.get_dummies(df, columns=['sex','embark_town'], drop_first=True)
df_en.head()

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton
0,0,3,22.0,1,0,7.2500,False,True,False,False,True
1,1,1,38.0,1,0,71.2833,False,False,True,False,False
2,1,3,26.0,0,0,7.9250,True,False,False,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,False,True
4,0,3,35.0,0,0,8.0500,True,True,False,False,True

In [ ]:
df_en.astype(int)

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton
0,0,3,22,1,0,7,0,1,0,0,1
1,1,1,38,1,0,71,0,0,1,0,0
2,1,3,26,0,0,7,1,0,0,0,1
3,1,1,35,1,0,53,0,0,0,0,1
4,0,3,35,0,0,8,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27,0,0,13,1,1,0,0,1
887,1,1,19,0,0,30,1,0,0,0,1
888,0,3,29,1,2,23,0,0,0,0,1
889,1,1,26,0,0,30,1,1,1,0,0
890,0,3,32,0,0,7,1,1,0,1,0

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Initialize the encoder
le = LabelEncoder()


df['sex'] = le.fit_transform(df['sex'])

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embark_town,alone,sex_encoded
0,0,3,1,22.0,1,0,7.2500,Southampton,False,1
1,1,1,0,38.0,1,0,71.2833,Cherbourg,False,0
2,1,3,0,26.0,0,0,7.9250,Southampton,True,0
3,1,1,0,35.0,1,0,53.1000,Southampton,False,0
4,0,3,1,35.0,0,0,8.0500,Southampton,True,1

In [ ]:
df.drop(columns=['sex_encoded'], inplace=True)
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embark_town  alone
0         0       3    1  22.0      1      0   7.2500  Southampton  False
1         1       1    0  38.0      1      0  71.2833    Cherbourg  False
2         1       3    0  26.0      0      0   7.9250  Southampton   True
3         1       1    0  35.0      1      0  53.1000  Southampton  False
4         0       3    1  35.0      0      0   8.0500  Southampton   True

In [ ]:

X = df_en.drop("survived", axis=1)
y = df_en["survived"]

# Train_test_split

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

# **LogisticRegression**

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
715    0
525    0
381    1
140    0
173    0
Name: survived, Length: 295, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [ ]:
accuracy_score(y_test,y_pred)

0.8

In [ ]:
confusion_matrix(y_test,y_pred)

array([[150,  25],
       [ 34,  86]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       175
           1       0.77      0.72      0.74       120

    accuracy                           0.80       295
   macro avg       0.79      0.79      0.79       295
weighted avg       0.80      0.80      0.80       295

In [ ]:
from sklearn.linear_model import LinearRegression
mode=LinearRegression()
mode.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred_lin=mode.predict(X_test_scaled)
y_pred_lin

array([ 0.15663746,  0.1995498 ,  0.11480971,  0.84251177,  0.73405011,
        0.85758282,  0.60609854,  0.06955751,  0.66201096,  0.87568602,
        0.33709409,  0.01691479,  0.37508041,  0.17734651,  0.18034569,
        0.93317422,  0.31642411,  0.60613665,  0.21707884,  0.2826164 ,
        0.09846981,  0.32342683,  0.60832415,  0.11543537,  0.07838755,
       -0.05861171,  0.40318986,  0.200753  , -0.03412294,  0.54621294,
        0.11887711,  0.58289594,  0.44666432,  0.55137603,  0.12303279,
        0.20620384,  0.35222305,  0.60609854,  0.92191606,  0.07520908,
        0.20425809,  0.09078709,  0.07528329,  0.12976516,  0.64970051,
        0.04020601,  0.11900345,  0.10319099,  0.09806274,  0.38573129,
        0.65614985,  0.73271823, -0.09979637,  0.39754765, -0.01431403,
        0.90545178,  0.19546834,  0.99825715,  0.66461077,  0.64982875,
        0.11065605,  0.80744427,  0.70872108,  0.34067991,  0.12976516,
        0.56976519,  0.27068503,  0.07805249,  0.20461019,  0.86800609,
        0.67795298,  0.93796069,  0.46142725,  0.88448829,  0.10253125,
        0.06630976,  0.60282977,  0.97830367,  0.64851615,  0.52617837,
       -0.11805698,  0.6840461 ,  0.90511654,  0.12975914,  0.33931828,
        0.28714846,  0.97056556,  0.93439526,  0.29432301,  0.07489827,
        0.18060215,  0.34386684,  0.21600474,  0.12975515,  0.07520908,
        0.08212394,  0.29166861,  0.01283333,  0.65667907,  0.08622542,
        0.20071829,  0.05320276,  1.00886071,  0.04092228,  0.07201452,
        0.10746388,  0.62706915,  0.27611912,  0.07475311,  0.40476807,
        0.84269634,  0.11244411,  0.96424215,  0.31513757,  0.43494054,
        0.11573415,  0.28000146,  0.28397385,  0.69572266,  0.38593263,
        0.12732481,  0.93555111,  0.71927327,  0.34642341,  0.09407754,
        0.42303368,  0.73823951,  0.49326913,  0.67152285,  0.1107884 ,
        0.60616072,  0.15663746,  0.19980587,  0.65455483,  0.39364779,
        0.73151476,  0.9615903 ,  0.07800436,  0.02483708,  0.61719232,
        0.11097288,  0.6434177 ,  0.21299738,  0.19565454,  0.47646388,
        0.6484296 ,  0.20483446,  0.05669866,  0.99187558,  0.02099626,
        0.17929046,  0.0982773 ,  0.12291045,  0.6271252 ,  0.07528329,
        0.07480201,  0.09859927,  0.60611659,  0.67606939,  0.57464015,
        0.20387803,  0.34098071,  0.16810131,  0.96090524,  0.13010605,
        0.37140446,  0.23220149,  0.84263016,  0.10663273,  0.05316667,
        0.54348957,  0.74497762,  0.3151857 ,  0.71745348,  0.12666907,
        0.17857455,  0.34744738,  0.73302364,  0.63487235,  0.27742852,
        0.23340469,  0.06583217,  0.10342054,  0.35611122,  0.62804176,
        0.27853075,  0.33282273,  0.07520908,  0.34528816,  0.63219031,
        0.03151774,  0.19224115,  0.13976867,  0.07883457,  0.65955852,
        0.83934961,  0.98384784,  0.18850862,  0.89693369,  0.33570392,
       -0.05334237,  0.55068342,  0.79625065,  0.41644038,  0.21816315,
        0.67702353,  0.07882653,  0.29551112,  0.18205579, -0.00757397,
        0.55953028,  0.07367023,  0.90213878,  0.12975312,  0.37508041,
        0.00968627,  0.68395956,  0.42825615,  0.76159505,  0.07489827,
        0.07520908,  0.70565661,  0.10308901,  0.34288177,  0.09398128,
        0.72121078,  0.10645225,  0.45387315,  0.72504692,  0.56665432,
        0.20549253,  0.9257163 ,  0.12976516,  0.65490995,  0.07557808,
        0.58290797,  0.87030148,  0.60022848,  0.967522  ,  0.14894842,
        0.11507703,  0.65158062,  0.17857455,  0.59149803,  0.15860093,
        0.08291603,  0.07528329,  0.10255127,  0.10632192,  0.25186158,
        0.5525183 ,  0.19939384,  0.12976516,  0.21000022,  0.24324156,
        0.08578226,  0.10670694,  0.76825081,  0.17914249,  0.70463961,
        0.90889769,  0.41338765,  0.64035323,  0.08659442,  0.32820274,
        0.19690153,  0.12740903,  0.3479156 ,  0.48732167,  0.07520908,
        0.6444376 ,  0.1227162 ,  0.13235508,  0.42194465,  0.65766599,
        0.07813671,  0.12315311,  0.31073744,  0.89783177,  0.16810131,
        0.02424895,  0.11438859,  0.88199281, -0.00736681,  0.33807761,
       -0.05683507,  0.60616072,  0.01796663,  0.29549321,  0.15585983,
        0.11875881,  0.08568177,  0.79097343,  0.67360043,  0.11072824])

In [ ]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
715    0
525    0
381    1
140    0
173    0
Name: survived, Length: 295, dtype: int64

# StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred_lin)
r2

0.4433005279809341

# KNeighbors (KNN)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors= 5)
knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = knn.predict(X_test_scaled)
y_pred_knn

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0])

In [ ]:
accuracy_score(y_test,y_pred_knn)

0.8101694915254237

In [ ]:
confusion_matrix(y_test,y_pred_knn)

array([[157,  18],
       [ 38,  82]])

In [ ]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.81      0.90      0.85       175
           1       0.82      0.68      0.75       120

    accuracy                           0.81       295
   macro avg       0.81      0.79      0.80       295
weighted avg       0.81      0.81      0.81       295

# Naive_bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
ModelNB=GaussianNB()
ModelNB.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred_nb=ModelNB.predict(X_test)
y_pred_nb

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
accuracy_score(y_test,y_pred_nb)

0.7864406779661017

In [ ]:
confusion_matrix(y_test,y_pred_nb)

array([[142,  33],
       [ 30,  90]])

In [ ]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82       175
           1       0.73      0.75      0.74       120

    accuracy                           0.79       295
   macro avg       0.78      0.78      0.78       295
weighted avg       0.79      0.79      0.79       295

# Naive Bayes for Scalled Data

In [ ]:
from sklearn.naive_bayes import GaussianNB
ModelNB=GaussianNB()
ModelNB.fit(X_train_scaled,y_train)

GaussianNB()

In [ ]:
y_pre=ModelNB.predict(X_test_scaled)
y_pre

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
accuracy_score(y_test,y_pre)

0.7796610169491526

In [ ]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.79      0.86      0.82       175
           1       0.77      0.66      0.71       120

    accuracy                           0.78       295
   macro avg       0.78      0.76      0.77       295
weighted avg       0.78      0.78      0.78       295

# **Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
md=DecisionTreeClassifier()
md.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_dt=md.predict(X_test_scaled)
y_pred_dt

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0])

In [ ]:
accuracy_score(y_test,y_pred_dt)

0.752542372881356

In [ ]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.78      0.82      0.80       175
           1       0.71      0.66      0.68       120

    accuracy                           0.75       295
   macro avg       0.74      0.74      0.74       295
weighted avg       0.75      0.75      0.75       295

In [ ]:
confusion_matrix(y_test,y_pred_dt)

array([[143,  32],
       [ 41,  79]])

# Support Vector Machine

In [ ]:
from sklearn.svm import SVC
model_svc=SVC(kernel='rbf')
model_svc.fit(X_train_scaled,y_train)

SVC()

In [ ]:
y_pred_svm=model_svc.predict(X_test_scaled)
y_pred_svm

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0])

In [ ]:
accuracy_score(y_test,y_pred_svm)

0.8169491525423729

In [ ]:
confusion_matrix(y_test,y_pred_svm)

array([[163,  12],
       [ 42,  78]])

In [ ]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86       175
           1       0.87      0.65      0.74       120

    accuracy                           0.82       295
   macro avg       0.83      0.79      0.80       295
weighted avg       0.82      0.82      0.81       295